### ISSUE TITLE
Inloggningen är säker och fungerar bra förutom en sak

### ISSUE THREAD

**Issue by me222wm** [nj222dt/1dv450_nj222dt#10]
Inloggningen verkar fungera bra. Du använder hashade lösenord med BCrypt och has_secure_password. 

Bra att du har hunnit implementera möjlighet för applikationen att komma ihåg användaren. Det verkar också fungera bra. Jag förblir inloggad även om jag stänger ner webbläsaren. Ett problem är bara att jag också förblir inloggad även om jag inte har kryssat i "Remember me on this computer". Jag tror att lösningen är att ta bort/kommentera ut [rad 11](https://github.com/nj222dt/1dv450_nj222dt/blob/master/Api_regi/app/controllers/sessions_controller.rb#L11)  så att det blir exakt som [här](https://www.railstutorial.org/book/log_in_log_out#code-remember_me_ternary).

**Comment by nj222dt** [comment]
Tror det kan vara fixat
