### ISSUE TITLE
Sammanställning

### ISSUE THREAD

**Issue by me222wm** [nj222dt/1dv450_nj222dt#12]
Hej! 

Här är en sammanfattning av min feedback. 

Angående installationen använde jag Cloud9-lösningen som fungerade utmärkt. I det stora hela tycker jag att applikationen fungerar bra och följer rails konventioner för crud-funktionalitet med "new", "create", "show" osv. Jag har endel småsaker att anmärka på i mina övriga issues, men det finns ett allvarligare problem - nämligen auktorisering. Du kontrollerar på ett bra att det krävs fullgoda uppgifter för att logga in (autentisering), men väl inloggad har jag som vanlig användare tillstånd att göra nästan vad som helst, t.ex. radera andra användares appar. Lyckligvis är det ganska enkelt att åtgärda. Läs [detta avsnitt](https://www.railstutorial.org/book/updating_and_deleting_users#sec-authorization) i Ruby on Rails tutorial där författaren går igenom ett par metoder för att kolla att det är rätt användare som försöker utföra olika handlingar.

**Comment by 1dv450** [comment]
Bra feedback med tydliga issues som jag hoppas gås igenom och åtgärdas (stäng issues när de är klara)

**Comment by nj222dt** [comment]
All issues fixed to the best of my ability
