### ISSUE TITLE
2 spaces indentation

### ISSUE THREAD

**Issue by me222wm** [nj222dt/1dv450_nj222dt#3]
Kanske en liten sak, men vissa filer (t.ex. apis_controller.rb) har fyra mellanslags indrag, med andra (t.ex. api.rb) har två. Enligt Ruby on Rails konventioner ska det vara två mellanslags indrag. http://www.caliban.org/ruby/rubyguide.shtml#indentation

**Comment by nj222dt** [comment]
Det är cloud9 som är jobbigt. Har andra prio's, Men ska tänka på i framtiden.
