### ISSUE TITLE
Felmeddelande försvinner inte

### ISSUE THREAD

**Issue by me222wm** [nj222dt/1dv450_nj222dt#5]
Ibland hänger felmeddelandet kvar. Om jag klickar på knappen "Log in" med fel uppgifter får jag som sig bör ett felmeddelande. Men om jag sedan loggar in med rätt uppgifter är felmeddelandet kvar även på nästa sida. Felet bör lösas om du ändrar från `flash[:danger]` till `flash.now[:danger]` på [denna rad](https://github.com/nj222dt/1dv450_nj222dt/blob/master/Api_regi/app/controllers/sessions_controller.rb#L14).

**Comment by nj222dt** [comment]
Fixat
