### ISSUE TITLE
Egenskapen i label mostvarar inte input-fältet 

### ISSUE THREAD

**Issue by me222wm** [nj222dt/1dv450_nj222dt#7]
När jag kör https://validator.w3.org/ får jag följande fel: "The for attribute of the label element must refer to a non-hidden form control." pga [den här raden](https://github.com/nj222dt/1dv450_nj222dt/blob/master/Api_regi/app/views/apis/new.html.erb#L4). Ett förslag är att skriva `<%= f.label:name, "Name of the application" %>`.

**Comment by nj222dt** [comment]
Fixed
