### ISSUE TITLE
Kommer fortfarande åt user-sidan efter utloggning

### ISSUE THREAD

**Issue by me222wm** [nj222dt/1dv450_nj222dt#9]
Jag hittade en bugg som återskapas på följande sätt:

1. Logga in. 
2. Logga ut. 
3. Klicka på browserns bakåtknapp. 
4. Jag är fortfarande inloggad. 
5. Klicka på t.ex. "Remove app". 
6. Applikationen krashar eftersom det inte finns någon "current user". 

Problemet har dels med cachning att göra (och är svårt att göra något åt), dels beror det på att det inte sker någon kontroll att det är en inloggad användare, samt rätt användare som försöker nå de olika metoderna destroy, new etc.

**Comment by nj222dt** [comment]
Kan inte fixa men man kna inte göra något nu, tror det är cachningen som fuckar mig
